### ISSUE TITLE
다운로드 로딩 애니메이션 개선

### ISSUE THREAD

**Issue by TroyTae** [croquiscom/create-zigzag-app#2]
https://github.com/croquiscom/create-zigzag-app/blob/master/index.js#L8-L16
현재는 아래 두 개를 교차하다가 완료되면 성공 메세지를 출력합니다.
```
Downloading...😄
Downloading...😝
```
용량 혹은 파일 갯수를 기준으로 얼마나 다운로드했는지 디텍팅해서 알려줄 수 있으면 좋을 것 같습니다.

**Comment by Shinye** [comment]
괜찮다면 제가 가져가고 싶습니다! 🙋

**Comment by Shinye** [comment]
https://github.com/jprichardson/node-fs-extra/issues/545
흠 일단은 오피셜하게 fs.copy과정에서 progress를 제공하진 않는 듯 하네요.. 할거면 다른 방법을 찾아봐야겠어요 :eyes: 간단하게 해결할수 있지 않을까 했는데 조금 더 리서치가 필요해보이네효

**Comment by TroyTae** [comment]
저도 좀 봤는데 파일 용량처럼 전체적인 사이즈를 구하는건 되는 것 같은데 진행상황 디텍팅은 힘든가보네요.
예전에 프론트에서 비슷한 상황에 썼던(실제로 많이 쓰는) 꼼수긴 한데 1초(30%) 2초(60%) 3초(90%) 무한대기 다운로드 완료(100%) 이런식으로 했던 기억이 있긴 합니다 ㅋㅋ
아 물론 1초만에 완료되면 30%에서 갑자기 100%로 훅 갑니다.

**Comment by TroyTae** [comment]
당장 깔끔한 해결책이 보이지 않아 우선 봉인
